// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Oj_iRRsgu4gLBfIyMdvq6FBxqTWaw4w',
    appId: '1:755121233171:web:7a1b3a72677ec2c4384ee6',
    messagingSenderId: '755121233171',
    projectId: 'unigovportal',
    authDomain: 'unigovportal.firebaseapp.com',
    storageBucket: 'unigovportal.firebasestorage.app',
    measurementId: 'G-H7JJC15W8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9-9J_MglVXW7AsUBC-cLZdUIAK92-vkg',
    appId: '1:755121233171:android:a2f72d6c87a7d062384ee6',
    messagingSenderId: '755121233171',
    projectId: 'unigovportal',
    storageBucket: 'unigovportal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNF_FtfTqH8h4mDygdZstCKAJKfngN4Qg',
    appId: '1:755121233171:ios:da6f9457c6621640384ee6',
    messagingSenderId: '755121233171',
    projectId: 'unigovportal',
    storageBucket: 'unigovportal.firebasestorage.app',
    iosBundleId: 'com.example.uniGovPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNF_FtfTqH8h4mDygdZstCKAJKfngN4Qg',
    appId: '1:755121233171:ios:da6f9457c6621640384ee6',
    messagingSenderId: '755121233171',
    projectId: 'unigovportal',
    storageBucket: 'unigovportal.firebasestorage.app',
    iosBundleId: 'com.example.uniGovPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Oj_iRRsgu4gLBfIyMdvq6FBxqTWaw4w',
    appId: '1:755121233171:web:4dd54e4e6b3ddc5b384ee6',
    messagingSenderId: '755121233171',
    projectId: 'unigovportal',
    authDomain: 'unigovportal.firebaseapp.com',
    storageBucket: 'unigovportal.firebasestorage.app',
    measurementId: 'G-LZ0QTEBB3N',
  );
}
